# Generated by Django 5.0.6 on 2024-05-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_url", models.URLField(max_length=600)),
                (
                    "short_code",
                    models.CharField(blank=True, max_length=15, null=True, unique=True),
                ),
            ],
        ),
    ]
